// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/rechtliches": {
    params: {};
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/rechtliches";
  };
  "./routes/_index.tsx": {
    id: "routes/_index";
    page: "/";
  };
  "./routes/rechtliches.tsx": {
    id: "routes/rechtliches";
    page: "/rechtliches";
  };
};

type RouteModules = {
  "root": typeof import("./app/root.tsx");
  "routes/_index": typeof import("./app/./routes/_index.tsx");
  "routes/rechtliches": typeof import("./app/./routes/rechtliches.tsx");
};